SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM (SELECT BOOK_ID, SALES_DATE, SALES
     FROM BOOK_SALES
     WHERE SALES_DATE LIKE '2022-01-__') AS S
     JOIN
     (SELECT *
     FROM BOOK) AS B
     ON S.BOOK_ID = B.BOOK_ID
     JOIN
     (SELECT *
     FROM AUTHOR) AS A
     ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY 1 ASC, 3 DESC