select I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
from ANIMAL_INS as I
join ANIMAL_OUTS as O
on I.ANIMAL_ID = O.ANIMAL_ID
where I.SEX_UPON_INTAKE LIKE 'Intact%' and (O.SEX_UPON_OUTCOME LIKE 'Spayed%' or O.SEX_UPON_OUTCOME LIKE 'Neutered%')
order by 1 asc