-- 코드를 작성해주세요
-- 연도별 max size sub table
SELECT E.YEAR, (MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM (SELECT *, year(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA) AS E
JOIN (SELECT year(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY year(DIFFERENTIATION_DATE)) AS S
ON E.YEAR = S.YEAR
ORDER BY 1, 2