SELECT sub.FLAVOR 
FROM (SELECT FIRST_HALF.FLAVOR, ICECREAM_INFO.INGREDIENT_TYPE,FIRST_HALF.TOTAL_ORDER 
      FROM FIRST_HALF
      JOIN ICECREAM_INFO
      ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR) AS sub
WHERE sub.INGREDIENT_TYPE = 'fruit_based' AND sub.TOTAL_ORDER > 3000
ORDER BY sub.TOTAL_ORDER DESC;
