-- 코드를 입력하세요
SELECT b.CATEGORY AS CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS a
JOIN BOOK AS b
ON a.BOOK_ID = b.BOOK_ID
WHERE SALES_DATE LIKE '2022-01___'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY