select count(*) as FISH_COUNT, MAX(LENGTH) as MAX_LENGTH, FISH_TYPE
from FISH_INFO
where FISH_TYPE IN (
select A.FISH_TYPE
from (
SELECT ID, FISH_TYPE, CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END AS ADJUSTED_LENGTH
FROM FISH_INFO) as A
group by A.FISH_TYPE
having AVG(A.ADJUSTED_LENGTH)>= 33)
group by FISH_TYPE
order by 3 asc